server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gvgroup_authorization
    username: user
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security: TRACE